frameworks:
- ["amr", "zho"]

encoder: /opt/data/private/slzhou/PLMs/chinese-roberta-wwm-ext-large
accumulation_steps: 1
batch_size: 8
query_length: 3
use_syn: false
add_fw: true
base_model: the model which adding fw without syntax